### ISSUE TITLE
Missing Licensing Information

### ISSUE THREAD

**Issue by gamaral** [tasanakorn/rpi-fbcp#17]
I want to add this package to Buildroot proper, but it's lacking any licensing information.
Is it BSD/MIT/GPL?

**Comment by tasanakorn** [comment]
@gamaral I don't have familiar about open source license. What do you recommend ?

**Comment by junland** [comment]
@tasanakorn Usually `GPLv2` or `MIT` are pretty good licenses. If you have any trouble choosing a license I would go [here](https://choosealicense.com/) or [here ](https://tldrlegal.com/)if you want a more extensive list and explanation of licenses. 

I am interested in using this in one of my projects however licensing is preventing me from using it. (Without a license I can't distribute or really fork the project.) Looking forward to a license getting placed in this repo.

**Comment by fhunleth** [comment]
I just ran into the lack of a license as well. Would it be possible to add one?

**Comment by tasanakorn** [comment]
Switch to MIT license.
If you have any suggestions please advise
